### ISSUE TITLE
fragmentManager Transaction

### ISSUE THREAD

**Issue by airblaster** [johncarl81/transfuse#103]
Hi,
how do you use a fragment Manager Transactions with Transfuse?
The following Code just returns an error because the fragment is an Transfuse fragment, not an Android Fragment:
```
            fragmentManager.beginTransaction()
                    .add(R.id.container, fragment)
                    .commit();
```

**Comment by johncarl81** [comment]
This should be implemented with the latest fragment / intent builder work.
