### ISSUE TITLE
Injection not working with EasyAdapter?

### ISSUE THREAD

**Issue by airblaster** [johncarl81/transfuse#111]
I'm using EasyAdapter (https://github.com/ribot/easy-adapter) in several places.
Today I tried to convert my AutoCompleteTextView to use an EasyAdapater, too.
However, unexpectedly the injection of the ProductService (a RetroFit Service) doesn't seem to work anymore - it stays null.
The code starts kind of like this:
```
public class AutoCompleteAdapter extends EasyAdapter<String> implements Filterable {

        @Inject
    @Named(Constants.SERVICE_PRODUCT)
    ProductService productService;

    @Inject
    public AutoCompleteAdapter( Context context, Class clazz) {
        super(context, clazz);
    }
```
This used to work well when I was still inheriting from ArrayAdapter.
Only noteable differences are:
- inheriting from EasyAdapter instead of ArrayAdapter
- implementing Filterable itself instead of overwriting ArrayAdapters implementation
- Additional constructor injection parameters

**Comment by johncarl81** [comment]
This is fixed.
