### ISSUE TITLE
Adding multiple listeners of the same listener type

### ISSUE THREAD

**Issue by airblaster** [johncarl81/transfuse#116]
It seems that the current implementation doesn't allow to register multiple listeners of the same type.
E.g. lets take a look at the AutoCompleteTextView onItemSelectedListener and how I'd add it to RegistrationAnalyzer.java:
```
listenerMethodMapping.put(AndroidLiterals.AUTO_COMPLETE_TEXT_VIEW, new HashMap<ASTType, String>());
listenerMethodMapping.get(AndroidLiterals.AUTO_COMPLETE_TEXT_VIEW).put(AndroidLiterals.ADAPTER_VIEW_ON_ITEM_SELECTED_LISTENER, "setOnItemSelectedListener");
```
However, AndroidLiterals.ADAPTER_VIEW_ON_ITEM_SELECTED_LISTENER has already been set for the AdapterView:
```
listenerMethodMapping.get(AndroidLiterals.ADAPTER_VIEW).put(AndroidLiterals.ADAPTER_VIEW_ON_ITEM_SELECTED_LISTENER, "setOnItemSelectedListener");
```
This leads to many tests erring because of duplicate keys:
```
  testMethodInjectionPointBuild(org.androidtransfuse.module.InjectionPointFactor
yTest): Multiple entries with same key: android.widget.AdapterView.OnItemSelecte
dListener=org.androidtransfuse.analysis.astAnalyzer.RegistrationAnalyzer$ViewReg
istrationGeneratorFactory@3a90b3b9 and android.widget.AdapterView.OnItemSelected
Listener=org.androidtransfuse.analysis.astAnalyzer.RegistrationAnalyzer$ViewRegi
strationGeneratorFactory@35d8c1f2
```
I wonder if there is a way to work around this problem.

**Comment by johncarl81** [comment]
It looks like the way we lookup and map listener types to their corresponding registration method makes this impossible.  I think we're going to cover the larger case of `OnItemSelectedListener` -> `AdapterView.setOnItemSelectedListener()` and leave this case (`AutoCompleteTextView`) to manually registered in an `@OnCreate`
