### ISSUE TITLE
passing arguments to fragments

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#122]
right now I manually create a generated fragment and then setArguments(Bundle) on it. Then in OnActivityCreated I can dig around in the bundle. It would be nice to have a mechanism similar to intent strategies for creating fragments with arguments.

**Comment by johncarl81** [comment]
Give this a try please: a05c0e3995360e9f4a9e47a6be606a00aa06a743

**Comment by dbachelder** [comment]
How does it work?

**Comment by johncarl81** [comment]
For each `@Fragment` we generate a FragmentFactory:
```java
@Fragment
class Example{
    @Inject @Extra("one") String one;
    @Inject @Extra(value = "two", optional = true) String two;
}
```
Generates:
```java
ExampleFragment fragment = new ExamleFragmentFactory("oneValue")
    .setTwo("twoValue")
    .build();
```
This manages the bundle and injects the extras into the annotated spots.

**Comment by johncarl81** [comment]
I also added IntentFactories for all other Transfuse components, similar to the IntentFactory Strategies:
```java
@Activity / @Service / @BroadcastReceiver
class Example{
    @Inject @Extra("one") String one;
    @Inject @Extra(value = "two", optional = true) String two;
}
```
Generates:
```java
Intent intent = new ExamleIntentFactory("oneValue")
    .setTwo("twoValue")
    .build(context);
```

These seems a little bit simplistic, I'm curious if this fits the need and if we should depreciate/remove the IntentFactory Strategies.

**Comment by johncarl81** [comment]
Reopen if this doesn't do the trick.
