### ISSUE TITLE
Modules don't seem to walk the inheritance tree

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#143]
`class Module extends BaseModule` where base module has some `@Provides` annotated methods are not considered providers for injection points.

**Comment by dbachelder** [comment]
maybe fixed as part of: 
https://github.com/johncarl81/transfuse/issues/165

does that change encompass this use case as well?

**Comment by dbachelder** [comment]
Nope, this still doesn't work.

**Comment by johncarl81** [comment]
I havent touched this yet unfortunately.
