### ISSUE TITLE
occasional NPE in Fragment.onDestroy

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#152]
Occasionally we are seeing these in our crash reporting tool... 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.company.Component$$AOPProxy$$0.onDestroy()' on a null object reference
       at com.company.ComponentFragment.onDestroy(ComponentFragment.java:207)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2006)
```

the null reference is the delegate..... so, not sure how this could be happening, unless the onCreateView() didn't complete for some reason?! 

needless to say, I can't reproduce this.. but though you should know.. perhaps there should be a null check.. or perhaps you see a reason this might happen, honestly I haven't dug into it deeply.

**Comment by johncarl81** [comment]
Thanks @dbachelder.  I seem to remember some null delegate issues around the `@Fragmnet` component.  Will check it out this afternoon.

**Comment by dbachelder** [comment]
@johncarl81 we are seeing this pretty frequently in production... any ideas?

**Comment by johncarl81** [comment]
Sounds like we'll need to add a null check in the fragment onDestroy.

**Comment by johncarl81** [comment]
This should to the trick: dfc395173dd56ea40894b2ea4c4cc774cec70b13

More of a bandaid, I'm really curious what the root cause is.

**Comment by dbachelder** [comment]
There seems to be a case when injecting a fragment into another fragment can result in a local variable in onCreate that is then referenced in the onDestroy

**Comment by dbachelder** [comment]
Looks fixed to me. We will obviously continue to monitor once it's in the wild
