### ISSUE TITLE
Annotate activity/fragment methods as view event listeners

### ISSUE THREAD

**Issue by goodsoft** [johncarl81/transfuse#155]
Something like this:
```java
@OnClick(R.id.button)
void onClick () {
    // do something
}
```
as an equivalent to
```java
findViewById(R.id.button).setOnClickListener(new View.OnClickListener () {
    public void onClick (View v) {
        // do something
    }
});
```

Would it be possible to implement such feature?

**Comment by johncarl81** [comment]
Yes.  Currently the technique we use is to leverage the listener type to match it up with the view:

```java
@RegisterListerer(R.id.button)
View.OnClickListener listener = new View.OnClickListener () {
    public void onClick (View v) {
        // do something
    }
}
```

See http://androidtransfuse.org/documentation.html#listener_registration

**Comment by goodsoft** [comment]
Yes, I'm aware of this feature.
The problem is it requires too much boilerplate code, introduces local field and requires verbose `android.view.View.OnClickListener` usage because of overlapping with `@View` inject annotation.
So I would really appreciate to be able to just annotate methods and leave Transfuse the task of generating all required anonymous classes.

**Comment by johncarl81** [comment]
Would this only support the `View.OnClickListener` then?

**Comment by goodsoft** [comment]
I suppose there should be a list of annotations for different events (just like for activity/fragment lifecycle callbacks): `OnClick`, `OnLongClick`, `OnItemClick` etc

**Comment by johncarl81** [comment]
Would you allow paramters in the annotated method?  Like an optional `View`?

**Comment by goodsoft** [comment]
Well, some methods would need arguments anyway, like, for example, `onKey(View v, int keyCode, KeyEvent event)`.
Not sure about whether they should be optional or required, though.

**Comment by johncarl81** [comment]
That's true.  Typically we've made these parameters optional, like with `onCreate`:
```java
@OnCreate
void one(){}
@OnCraete
void two(Bundle bundle){}
```

**Comment by goodsoft** [comment]
Probably it should be the same way here.
Less `android.view.View` verbosity in the code :)

**Comment by johncarl81** [comment]
Yup, agreed.  Would you like to try your hand at a PR?

**Comment by goodsoft** [comment]
If I manage to understand how the thing works... :D

**Comment by johncarl81** [comment]
If anyone wants to take a crack at this, go for it and open a PR.  Otherwise I'm closing this issue for now.
