### ISSUE TITLE
@Extra injection in fragments

### ISSUE THREAD

**Issue by goodsoft** [johncarl81/transfuse#160]
Currently injecting extra in fragment generates the code, which get the extra from `this.getActivity().getIntent().getExtras()`.
I think it should instead use `this.getArguments()` as extras can be passed to fragment itself via `fragment.setArguments(Bundle)`.
If we still want to be able to inject extras from containing activity, there should be an additional annotation for fragment arguments.

**Comment by goodsoft** [comment]
Oh, I see several open issues about this (#122, #138), so I'll close this.

**Comment by johncarl81** [comment]
Yeah, I'm looking at this right now in fact.
