### ISSUE TITLE
Feature request: inject extras from intent into BroadcastReceiver

### ISSUE THREAD

**Issue by goodsoft** [johncarl81/transfuse#162]
I think it would be a useful feature to inject extras from `intent.getExtras()` in `BroadcastReceiver`'s `onReceive` callback using `@Extra` annotation.

**Comment by johncarl81** [comment]
Hmm, not a bad idea.  I'd also love to have a Fragment Factory wtih `@Extras`.

**Comment by goodsoft** [comment]
By the way, what do you think about repopulating injected `@Extra`s from new intent in `@OnNewIntent` callback?

**Comment by johncarl81** [comment]
That's a tricky one, because `@Extras` are technically injected into the object graph, so reinjecting them would require us to keep references throughout the graph.

**Comment by johncarl81** [comment]
Added a quick implementation, let me know if this does the trick for you: https://github.com/johncarl81/transfuse/commit/b4fc691d1884ee50a027b196ed3307f3e056d8a6

**Comment by johncarl81** [comment]
Reopen if this doesn't work for you @goodsoft
