### ISSUE TITLE
null @Parcel @Extra throws exception

### ISSUE THREAD

**Issue by justincpollard** [johncarl81/transfuse#208]
I'm trying to pass an `@Parcel` annotated `@Extra` into my activity like so:

```java
@Activity(...)
public class DetailController {

  @Inject
  public DetailController(@Extra(value = "theParcel", optional = true) DetailModel model) {
    ...
  }
}
```

The `DetailModel` class is annotated with `@Parcel` from your Parceler library.

Since this param is optional, sometimes it will be null. Unfortunately, when it is null, the app crashes with this exception:

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.parceler.ParcelWrapper.getParcel()' on a null object reference`

It looks like the generated code doesn't take into account that a `@Parcel` could be null; it calls `ParcelWrapper.getParcel()` anyway:

`((DetailModel)((ParcelWrapper) ExtraUtil.getExtra(this.getIntent().getExtras(), "theParcel", true)).getParcel())`

**Comment by justincpollard** [comment]
Hey John! We're actually using `0.3.0-beta-9`. Thanks for the quick response :-)

**Comment by johncarl81** [comment]
^ That should do the trick.  Could you try it out?

**Comment by justincpollard** [comment]
Hey John, I'll try to take a look next week; off on a brief weekend vacation. Thanks for looking into this :-)

**Comment by johncarl81** [comment]
Cool, thanks for reporting the issue.  Let me know when you get back around to it.

**Comment by justincpollard** [comment]
Hey John, sorry I never got to this :-( I've been head down for the past 2 months on a feature we're releasing this week.

**Comment by johncarl81** [comment]
Quite alright.  I've done quite a bit of testing around this feature and it was about time to clean up the open PRs.  Of course, let me know if you have any issues.
