### ISSUE TITLE
Code generate content provider and sqlite boiler plate

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#91]
I've been using this project:

https://bitbucket.org/qbusict/cupboard/overview

It's awesome for reducing how much code I'm writing for sqlite and contentprovider access... Unfortunately it does use reflection to do its business.. it would kick ass to have the same feature set with generated code... maybe a sister project? Just something to think about in your spare time ;)

**Comment by johncarl81** [comment]
Closing for now... reopen if any good ideas come up!

BTW, we're working on a code generator for Cupboard currently: https://github.com/johncarl81/cupboard-procesor
